#!/usr/bin/env bash
# Configures /etc/hosts to redirect localhost and facebook.com
# localhost ünvanını 127.0.0.2 olaraq dəyişirik
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/g' /etc/hosts

# facebook.com domenini 8.8.8.8 IP-sinə yönləndiririk (əgər artıq yoxdursa)
if ! grep -q "facebook.com" /etc/hosts; then
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
